### ISSUE TITLE
Not able to run 

### ISSUE THREAD

**Issue by sairaut** [tnguyen14/apple-pay-web-example#3]
Hi,

I am trying to run this project on Azure site. I have followed the instructions from ReadMe.Md file and deployed the code to azure. I also ran the 'npm start' commend on the same directory where the code is deployed in azure through DebugConsole. but it is showing errors.  

Also, when i am clicking on the "Apple Pay" button (below sunglass), the action sheet is showing up for 3-4 seconds and getting minimized in 3-4 seconds without any reason. Action sheet is showing Processing icon but now moving further. 

Is there a need to change the env file? what all other changes i need to do in which files? Can you share some sample values?

**Comment by tnguyen14** [comment]
Hi,

That behavior is usually due to your domain not being registered on the Apple Pay Developer portal.

Could you share your merchant ID configuration page to make sure it's registered properly?

An example `.env` file would be:

```
MERCHANT_ID=merchant.com.test.merchantid
MERCHANT_NAME=Apple Pay Test
MERCHANT_DOMAIN=lab.tridnguyen.com
AUTHORIZED_ORIGINS=lab.tridnguyen.com
```

**Comment by marimogit** [comment]
Hi, I am trying to run your sample on MacOS 10.12.3 with node js v6.10.0 but failed. I have already create .env under web-payments-example dir and run cmd "npm start" there. Any hints to solve the problem? Sorry for my stupid question, I am very new to node js.


SD5-MacBook-Pro:web-payments-example gykho$ npm start

> web-payments-example@1.0.0 start /Users/gykho/Documents/web-payments-example
> forever start server/index.js && forever logs -f 0

warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: server/index.js
data:    server/index.js:25394 - { Error: ENOENT: no such file or directory, open '.env'
data:    server/index.js:25394 -     at Error (native)
data:    server/index.js:25394 -     at Object.fs.openSync (fs.js:640:18)
data:    server/index.js:25394 -     at Object.fs.readFileSync (fs.js:508:33)
data:    server/index.js:25394 -     at Object.config (/Users/gykho/Documents/web-payments-example/node_modules/dotenv/lib/main.js:30:37)
data:    server/index.js:25394 -     at Object.config (/Users/gykho/Documents/web-payments-example/node_modules/dotenv-safe/index.js:25:16)

**Comment by tnguyen14** [comment]
Apologies for the late reply. Been a busy month for me changing job.

Could you show the results of `ls -al`? Weird that it's complaining about `.env` not exist when you said you created it.

**Comment by marimogit** [comment]
I already found another github project and get my things done. Thank you.

**Comment by nelsieborja** [comment]
Got same issue .env file is there but log's saying file doesn't exist
@marimogit please can u share the github project?
